//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databasefirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class datapost
    {
        public int postid { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public System.DateTime datapublished { get; set; }
    }
}
